services:
  backend:
    build:
      context: .
      dockerfile: ./app_backend/Dockerfile.backend
    container_name: physh_backend
    ports:
      - "8000:8000"
    # Mount local HuggingFace cache for persistent model weights across restarts
    volumes:
      - hf_cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s #Check and increase
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./streamlit/Dockerfile.frontend
    container_name: physh_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8501/_stcore/health')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
      

volumes:
  hf_cache: